### ISSUE TITLE
Where Do I Download Everything

### ISSUE THREAD

**Issue by ThatRandomBeanerBeamer** [0x00G/NiceRAT#65]
Where can I download all the info?
Is there a command I need to do, is there something I need to config in the builder?
![Screenshot 2024-04-26 125540](https://github.com/0x00G/NiceRAT/assets/167591482/2f256657-a053-4e7b-af60-0a3819878a7a)

**Comment by 0x00G** [comment]
Upload to filehost failed, dose it happen to all PC's u tried it on?

**Comment by ThatRandomBeanerBeamer** [comment]
> Upload to filehost failed, dose it happen to all PC's u tried it on?

I have only tried it on mine, but I need to know it works before I start using it, or else I'll just use my FUD quasar build for now
