### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gabjohn3** [0x00G/NiceRAT#66]
Hi , tool not working it doesnt send info through webhook 
pls check if something is wrong

**Comment by 0x00G** [comment]
Everyone else reports that it works fine, so the problem may be in your setup.

**Comment by gabjohn3** [comment]
hmmmm very rare because i using some vms for testing purpose buddy and doesnt send the info o.o

**Comment by 0x00G** [comment]
It's because you are testing it in a VM, in NiceRAT.py (lines 46-50) there is an antidebug part that doesn't start the payload if the debugger or the VM detects it.

**Comment by gabjohn3** [comment]
Hmmm weird i deleted basically all anti vm features and info not send to webhook bro to discord O.O very rare
i ejecuted script alone and with pyinstaller nope, not working O.O i replaced webhook with one mine and nope still not working o.O

**Comment by Silentsniper1** [comment]
> Hi , tool not working it doesnt send info through webhook pls check if something is wrong

contact me on discord ill help u out my username is Silentsniper0
